services:
  database:
    image: postgres:16
    container_name: database
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - tamdb_data:/var/lib/postgresql/data
    networks:
      - tam-network

  # redis:
  #   image: redis:7.2-alpine
  #   container_name: redis
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - tam-network

  backend:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    container_name: backend
    env_file:
      - ./.env
    depends_on:
      - database
    networks:
      - tam-network
    ports:
      - "8000:8000"
    expose:
      - "8000"

  # celery:
  #   build:
  #     context: .
  #     dockerfile: ./docker/django/Dockerfile
  #   container_name: celery
  #   command: celery -A core worker -l INFO
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - redis
  #     - backend
  #   networks:
  #     - tam-network

  frontend:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    container_name: frontend
    networks:
      - tam-network
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  tamdb_data:


networks:
  tam-network:
